### ISSUE TITLE
Sailor does not work if ELSTICIO_API_URI conatins / at the end 

### ISSUE THREAD

**Issue by anton-kotenko** [elasticio/sailor-nodejs#70]
In case when env variable ELASTICIO_API_URI contains "/" symbol at the end (```http://192.168.39.1:9000/````)  sailor sends incorrect request to api and fails with error:  

````
Error happened: Cannot GET //v1/tasks/5aaa9ef8de5ff030189776dd/steps/step_1

Error: Cannot GET //v1/tasks/5aaa9ef8de5ff030189776dd/steps/step_1

    at checkStatusCode (/app/node_modules/elasticio-rest-node/lib/resource.js:104:29)
    at /app/node_modules/q/q.js:1249:26
    at _fulfilled (/app/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/app/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/app/node_modules/q/q.js:816:13)
    at /app/node_modules/q/q.js:570:49
    at runSingle (/app/node_modules/q/q.js:137:13)
    at flush (/app/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```
Seams that  sailor just concatenates prefix of api uri and path to endpoint. This produces url with doubled '/'. What todo: use path module for concatenations.

**Comment by drobiazko** [comment]
@anton-kotenko check this out: https://github.com/elasticio/elasticio-rest-node/pull/19
